In [22]:
%config IPCompleter.use_jedi = False
%pdb off
%load_ext autoreload
%autoreload 3
from pathlib import Path
import pathlib
import numpy as np
import pandas as pd

# required to enable non-blocking interaction:
%gui qt5

## Pho's Custom Libraries:
from pyphocorehelpers.Filesystem.path_helpers import find_first_extant_path
from pyphocorehelpers.function_helpers import function_attributes

# pyPhoPlaceCellAnalysis:
# NeuroPy (Diba Lab Python Repo) Loading
from neuropy.core.session.Formats.BaseDataSessionFormats import DataSessionFormatRegistryHolder
from neuropy.core.session.Formats.Specific.BapunDataSessionFormat import BapunDataSessionFormatRegisteredClass
from neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat import KDibaOldDataSessionFormatRegisteredClass
from neuropy.core.session.Formats.Specific.RachelDataSessionFormat import RachelDataSessionFormat
from neuropy.core.session.Formats.Specific.HiroDataSessionFormat import HiroDataSessionFormatRegisteredClass

## For computation parameters:
from neuropy.utils.result_context import IdentifyingContext
from neuropy.core.session.Formats.BaseDataSessionFormats import find_local_session_paths

# from PendingNotebookCode import _perform_batch_plot, _build_batch_plot_kwargs
# from pyphoplacecellanalysis.General.Batch.NonInteractiveProcessing import batch_load_session, batch_extended_computations, SessionBatchProgress, batch_programmatic_figures, batch_extended_programmatic_figures
# from pyphoplacecellanalysis.General.Pipeline.NeuropyPipeline import PipelineSavingScheme
from pyphoplacecellanalysis.General.Pipeline.Stages.Loading import saveData, loadData
import pyphoplacecellanalysis.General.Batch.runBatch
from pyphoplacecellanalysis.General.Batch.runBatch import BatchRun, BatchResultAccessor, run_diba_batch, BatchSessionCompletionHandler
from pyphoplacecellanalysis.General.Pipeline.NeuropyPipeline import PipelineSavingScheme


Automatic pdb calling has been turned OFF
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:

active_global_batch_result_filename='global_batch_result_2023-07-07.pkl'
debug_print=True
enable_neptune = False

if enable_neptune:
    import neptune # for logging progress and results
    from neptune.types import File
    from pyphoplacecellanalysis.General.Batch.NeptuneAiHelpers import set_environment_variables, neptune_output_figures
    neptune_kwargs = {'project':"commander.pho/PhoDibaLongShort2023",
    'api_token':"eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIxOGIxODU2My1lZTNhLTQ2ZWMtOTkzNS02ZTRmNzM5YmNjNjIifQ=="}
    set_environment_variables(neptune_kwargs)

In [15]:
""" 
from pyphoplacecellanalysis.General.Batch.runBatch import main, BatchRun, run_diba_batch, run_specific_batch

"""
global_data_root_parent_path = find_first_extant_path([Path(r'W:\Data'), Path(r'/media/MAX/Data'), Path(r'/Volumes/MoverNew/data'), Path(r'/home/halechr/turbo/Data')])
assert global_data_root_parent_path.exists(), f"global_data_root_parent_path: {global_data_root_parent_path} does not exist! Is the right computer's config commented out above?"

## NEPTUNE:
if enable_neptune:
	project = neptune.init_project(**neptune_kwargs)
	project["general/global_batch_result_filename"] = active_global_batch_result_filename
	project["general/global_data_root_parent_path"] = global_data_root_parent_path.as_posix()

## TODO: load the batch result initially:

## Build Pickle Path:
global_batch_result_file_path = Path(global_data_root_parent_path).joinpath(active_global_batch_result_filename).resolve() # Use Default

if enable_neptune:
	run = neptune.init_run() # rember to run.stop()
	run['parameters/global_batch_result_file_path'] = global_batch_result_file_path.as_posix()
	# project["general/data_analysis"].upload("data_analysis.ipynb")
	run["dataset/latest"].track_files(f"file://{global_batch_result_file_path}") # "s3://datasets/images"

# try to load an existing batch result:
global_batch_run = BatchRun.try_init_from_file(global_data_root_parent_path, active_global_batch_result_filename=active_global_batch_result_filename, debug_print=debug_print) # on_needs_create_callback_fn=run_diba_batch
batch_progress_df = global_batch_run.to_dataframe(expand_context=True, good_only=False) # all
good_only_batch_progress_df = global_batch_run.to_dataframe(expand_context=True, good_only=True)

if enable_neptune:
	run["dataset/global_batch_run_progress_df"].upload(File.as_html(batch_progress_df)) # "path/to/test_preds.csv"
	run["dataset/global_batch_run_good_only_df"].upload(File.as_html(good_only_batch_progress_df)) # "path/to/test_preds.csv"
	
batch_progress_df

finalized_loaded_global_batch_result_pickle_path: /nfs/turbo/umms-kdiba/Data/global_batch_result_2023-07-07.pkl
Loading loaded session pickle file results : /nfs/turbo/umms-kdiba/Data/global_batch_result_2023-07-07.pkl... encountered exception 'BatchRun' object is not iterable while printing. Turning into a warning and continuing.
done.
no difference between provided and internal paths.


format_name animal exper_name        session_name  \
0        kdiba  gor01        one  2006-6-07_11-26-53   
1        kdiba  gor01        one  2006-6-08_14-26-15   
2        kdiba  gor01        one   2006-6-09_1-22-43   
3        kdiba  gor01        one   2006-6-09_3-23-37   
4        kdiba  gor01        one  2006-6-12_15-55-31   
..         ...    ...        ...                 ...   
67       kdiba  pin01        one    fet11-04_21-20-3   
68       kdiba  pin01        one           redundant   
69       kdiba  pin01        one            showclus   
70       kdiba  pin01        one               sleep   
71       kdiba  pin01        one               tmaze   

                               context  \
0   kdiba_gor01_one_2006-6-07_11-26-53   
1   kdiba_gor01_one_2006-6-08_14-26-15   
2    kdiba_gor01_one_2006-6-09_1-22-43   
3    kdiba_gor01_one_2006-6-09_3-23-37   
4   kdiba_gor01_one_2006-6-12_15-55-31   
..                                 ...   
67    kdiba_pin01_one_fet11-04_21-20-3   
68           kdiba_pin01_one_redundant   
69            kdiba_pin01_one_showclus   
70               kdiba_pin01_one_sleep   
71               kdiba_pin01_one_tmaze   

                                             basedirs  \
0   /nfs/turbo/umms-kdiba/Data/KDIBA/gor01/one/200...   
1   /nfs/turbo/umms-kdiba/Data/KDIBA/gor01/one/200...   
2   /nfs/turbo/umms-kdiba/Data/KDIBA/gor01/one/200...   
3   /nfs/turbo/umms-kdiba/Data/KDIBA/gor01/one/200...   
4   /nfs/turbo/umms-kdiba/Data/KDIBA/gor01/one/200...   
..                                                ...   
67  /nfs/turbo/umms-kdiba/Data/KDIBA/pin01/one/fet...   
68  /nfs/turbo/umms-kdiba/Data/KDIBA/pin01/one/red...   
69  /nfs/turbo/umms-kdiba/Data/KDIBA/pin01/one/sho...   
70   /nfs/turbo/umms-kdiba/Data/KDIBA/pin01/one/sleep   
71   /nfs/turbo/umms-kdiba/Data/KDIBA/pin01/one/tmaze   

                            status  \
0   SessionBatchProgress.COMPLETED   
1   SessionBatchProgress.COMPLETED   
2   SessionBatchProgress.COMPLETED   
3      SessionBatchProgress.FAILED   
4   SessionBatchProgress.COMPLETED   
..                             ...   
67  SessionBatchProgress.COMPLETED   
68     SessionBatchProgress.FAILED   
69     SessionBatchProgress.FAILED   
70     SessionBatchProgress.FAILED   
71     SessionBatchProgress.FAILED   

                                               errors  n_long_laps  \
0                                                None           45   
1                                                None           40   
2                                                None           42   
3              need at least one array to concatenate            0   
4                                                None           40   
..                                                ...          ...   
67                                               None           70   
68  Required File: /nfs/turbo/umms-kdiba/Data/KDIB...            0   
69  Required File: /nfs/turbo/umms-kdiba/Data/KDIB...            0   
70  Required File: /nfs/turbo/umms-kdiba/Data/KDIB...            0   
71  Required File: /nfs/turbo/umms-kdiba/Data/KDIB...            0   

    n_long_replays  n_short_laps  n_short_replays  is_ready  \
0              322             2               65     False   
1              198            40              166      True   
2              122            40               81      True   
3                0             0                0     False   
4               30            34               34      True   
..             ...           ...              ...       ...   
67               0            66                4     False   
68               0             0                0     False   
69               0             0                0     False   
70               0             0                0     False   
71               0             0                0     False   

                       global_computation_result_file  \
0   /nfs/turbo/umms-kdiba/Da

In [ ]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    # display(batch_progress_df)
    display(good_only_batch_progress_df)

In [ ]:
good_only_batch_progress_df.info()

In [ ]:
from pyphoplacecellanalysis.General.Batch.PhoDiba2023Paper import UserAnnotationsManager

user_is_replay_good_annotations = UserAnnotationsManager.get_user_annotations()

good_only_batch_progress_df['has_user_replay_annotations'] = [(a_row_context.adding_context_if_missing(display_fn_name='DecodedEpochSlices',epochs='replays',decoder='long_results_obj',user_annotation='selections') in user_is_replay_good_annotations) for a_row_context in good_only_batch_progress_df['context']]
good_only_batch_progress_df

In [ ]:
for index, row in good_only_batch_progress_df.iterrows():
    if row['is_ready']:
        row_context = row['context']
        print(f"context: {row_context}")
        row_context in user_is_replay_good_annotations
    

# Build `global_batch_run` pre-loading results (before execution)

In [ ]:
# global_batch_result = loadData('global_batch_result.pkl')
global_batch_run = run_diba_batch(global_data_root_parent_path, execute_all=False, extant_batch_run=global_batch_run, debug_print=False)
# print(f'global_batch_result: {global_batch_run}')
global_batch_run

# Run Batch Executions/Computations

In [16]:
## I got it doing the bare-minimum loading and computations, so it should be ready to update the laps and constraint the placefields to those. Then we should be able to set up the replays at the same time.
# finally, we then finish by computing.
# force_reload = True
force_reload = False
result_handler = BatchSessionCompletionHandler(force_reload_all=force_reload)

## Execute with the custom arguments.
active_computation_functions_name_includelist=['_perform_baseline_placefield_computation',
                                        # '_perform_time_dependent_placefield_computation',
                                        '_perform_extended_statistics_computation',
                                        '_perform_position_decoding_computation', 
                                        '_perform_firing_rate_trends_computation',
                                        '_perform_pf_find_ratemap_peaks_computation',
                                        # '_perform_time_dependent_pf_sequential_surprise_computation'
                                        '_perform_two_step_position_decoding_computation',
                                        # '_perform_recursive_latent_placefield_decoding'
                                    ]
# active_computation_functions_name_includelist=['_perform_baseline_placefield_computation']
global_batch_run.execute_all(force_reload=force_reload, saving_mode=PipelineSavingScheme.SKIP_SAVING, skip_extended_batch_computations=True, post_run_callback_fn=result_handler.on_complete_success_execution_session,
                                                                                        **{'computation_functions_name_includelist': active_computation_functions_name_includelist,
                                                                                            'active_session_computation_configs': None,
                                                                                            'allow_processing_previously_completed': True}) # can override `active_session_computation_configs` if we want to set custom ones like only the laps.)

# 4m 39.8s

enable_calling_completion_handler_for_previously_completed: True
basedir: /nfs/turbo/umms-kdiba/Data/KDIBA/gor01/one/2006-6-07_11-26-53
active_data_mode_name: kdiba
Loading loaded session pickle file results : /nfs/turbo/umms-kdiba/Data/KDIBA/gor01/one/2006-6-07_11-26-53/loadedSessPickle.pkl... done.
Loading pickled pipeline success: /nfs/turbo/umms-kdiba/Data/KDIBA/gor01/one/2006-6-07_11-26-53/loadedSessPickle.pkl.
property already present in pickled version. No need to save.
build_lap_only_short_long_bin_aligned_computation_configs(...):
	len(active_session_computation_configs): 1
	len(final_active_session_computation_configs): 1
using provided computation_functions_name_includelist: ['_perform_baseline_placefield_computation', '_perform_extended_statistics_computation', '_perform_position_decoding_computation', '_perform_firing_rate_trends_computation', '_perform_pf_find_ratemap_peaks_computation', '_perform_two_step_position_decoding_computation']
	 TODO: this will prevent recomput

In [ ]:
# last completed:
r'W:\Data\KDIBA\pin01\one\11-03_12-3-25'

In [17]:
# Save to file:
saveData(global_batch_result_file_path, global_batch_run) # Update the global batch run dictionary

[autoreload of pyphoplacecellanalysis.General.Batch.runBatch failed: Traceback (most recent call last):
  File "/scratch/kdiba_root/kdiba/.cache/pypoetry/virtualenvs/spike3d-xhKu_1Lg-py3.9/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 274, in check
    superreload(m, reload, self.old_objects, self.shell)
  File "/scratch/kdiba_root/kdiba/.cache/pypoetry/virtualenvs/spike3d-xhKu_1Lg-py3.9/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 500, in superreload
    update_generic(old_obj, new_obj)
  File "/scratch/kdiba_root/kdiba/.cache/pypoetry/virtualenvs/spike3d-xhKu_1Lg-py3.9/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 397, in update_generic
    update(a, b)
  File "/scratch/kdiba_root/kdiba/.cache/pypoetry/virtualenvs/spike3d-xhKu_1Lg-py3.9/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 365, in update_class
    update_instances(old, new)
  File "/scratch/kdiba_root/kdiba/.cache/pypoetry/virtualenvs/sp

Saving (file mode 'w+b') saved session pickle file results : /nfs/turbo/umms-kdiba/Data/global_batch_result_2023-07-07.pkl... done.


In [40]:
## Save the instantaneous firing rate results dict: (# Dict[IdentifyingContext] = InstantaneousSpikeRateGroupsComputation)
inst_fr_output_filename = 'long_short_inst_firing_rate_result_handlers.pkl'
global_batch_result_inst_fr_file_path = Path(global_data_root_parent_path).joinpath(inst_fr_output_filename).resolve() # Use Default
print(f'global_batch_result_inst_fr_file_path: {global_batch_result_inst_fr_file_path}')


global_batch_result_inst_fr_file_path: /nfs/turbo/umms-kdiba/Data/long_short_inst_firing_rate_result_handlers.pkl


In [ ]:

# Save the all sessions instantaneous firing rate dict to the path:
saveData(global_batch_result_inst_fr_file_path, result_handler.to_dict())

In [37]:
# result_handler.__dir__()
# getattr(result_handler, 'across_sessions_instantaneous_fr_dict')
str(result_handler)
from attrs import asdict, astuple

# asdict(result_handler)
# astuple(result_handler)
type(result_handler)

result_handler.

pyphoplacecellanalysis.General.Batch.runBatch.BatchSessionCompletionHandler

In [45]:
num_sessions = len(result_handler.across_sessions_instantaneous_fr_dict)
print(f'num_sessions: {num_sessions}')


TypeError: descriptor 'across_sessions_instantaneous_fr_dict' for 'BatchSessionCompletionHandler' objects doesn't apply to a 'BatchSessionCompletionHandler' object

In [43]:
import dill

dill.dump(result_handler, str(global_batch_result_inst_fr_file_path))

TypeError: file must have a 'write' attribute

In [10]:
accumulated_lists = []

for a_ctxt, a_inst_result in result_handler.across_sessions_instantaneous_fr_dict.items():
	print(f'{a_ctxt} - {a_inst_result.Fig2_Laps_FR[2]}') # .cell_agg_inst_fr_list	
	# [(v.cell_agg_inst_fr_list.mean(), v.cell_agg_inst_fr_list.std(), v.cell_agg_inst_fr_list) for v in (a_inst_result.LxC_ThetaDeltaMinus, a_inst_result.LxC_ThetaDeltaPlus, a_inst_result.SxC_ThetaDeltaMinus, a_inst_result.SxC_ThetaDeltaPlus)]
	accumulated_lists.append([v.cell_agg_inst_fr_list for v in (a_inst_result.LxC_ThetaDeltaMinus, a_inst_result.LxC_ThetaDeltaPlus, a_inst_result.SxC_ThetaDeltaMinus, a_inst_result.SxC_ThetaDeltaPlus)])
	
# a_inst_result.LxC_ReplayDeltaMinus, a_inst_result.LxC_ReplayDeltaPlus, a_inst_result.SxC_ReplayDeltaMinus, a_inst_result.SxC_ReplayDeltaPlus
# a_inst_result.LxC_ThetaDeltaMinus, a_inst_result.LxC_ThetaDeltaPlus, a_inst_result.SxC_ThetaDeltaMinus, a_inst_result.SxC_ThetaDeltaPlus
accumulated_lists


kdiba_gor01_one_2006-6-08_14-26-15 - (25.06361650588731, 16.283850148108478, array([ 3.9894228 ,  2.9920671 , 28.57453673,  7.72139413, 46.71840499,
       21.985472  , 30.21114823, 35.19616098, 48.18394158]))
kdiba_gor01_one_2006-6-12_15-55-31 - (16.46178092086152, 18.260259784367754, array([ 2.04586166, 42.22483648,  5.11464462]))
kdiba_gor01_two_2006-6-07_16-40-19 - (12.053651149676085, 8.067478755367544, array([ 8.79627034,  4.21300035, 23.15168276]))
kdiba_pin01_one_11-02_17-46-44 - (6.563356593303122, 6.028757991544125, array([ 3.71376888,  4.27438158, 16.84048206,  1.42479386]))


[[array([35.15251441, 41.66069477,  4.98677851, 15.37395496, 35.26129489,
         59.11900795, 72.06217233, 78.23503774, 33.38138055, 71.42532107,
         39.01980517]),
  array([ 1.04984811,  4.83615749, 37.52227742,  8.22104659, 46.18848211,
         57.02860977, 60.23678129, 67.14828879, 13.05720408, 34.18458494,
          8.39878485]),
  array([ 3.9894228 ,  2.9920671 , 28.57453673,  7.72139413, 46.71840499,
         21.985472  , 30.21114823, 35.19616098, 48.18394158]),
  array([64.86207382, 15.55832058, 32.5795723 , 54.43506117, 89.47034065,
         87.56794323, 56.39326417, 34.39523235, 50.68358128])],
 [array([53.91624642, 34.53489175]),
  array([42.73940483, 10.56023683]),
  array([ 2.04586166, 42.22483648,  5.11464462]),
  array([55.32011319, 78.10938131, 47.20812508])],
 [array([ 2.9920671 , 47.64688215, 49.21735085]),
  array([11.19271548, 38.63748587, 22.00260583]),
  array([ 8.79627034,  4.21300035, 23.15168276]),
  array([ 37.93185138, 112.47223249,  61.53900402])],
 [

In [13]:
from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.SpikeAnalysis import SpikeRateTrends

all_LxC_ThetaDeltaMinus = SpikeRateTrends([], []) # empty lists
all_LxC_ThetaDeltaMinus.inst_fr_df_list.append(

SpikeRateTrends(inst_fr_df_list=[], inst_fr_signals_list=[], epoch_agg_inst_fr_list=NOTHING, cell_agg_inst_fr_list=NOTHING, all_agg_inst_fr=NOTHING)

In [11]:
np.vstack(accumulated_lists)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 2 has size 3

In [ ]:

v.cell_agg_inst_fr_list


In [ ]:
# Get output files:
batch_progress_df = global_batch_run.to_dataframe(expand_context=True, good_only=False) # all
batch_progress_df.
good_only_batch_progress_df = global_batch_run.to_dataframe(expand_context=True, good_only=True)
good_only_batch_progress_df

## Single Session testing:


In [ ]:
_test_out = global_batch_run.execute_session(session_context=curr_sess_context, force_reload=True, skip_extended_batch_computations=True, computation_functions_name_includelist =['_perform_baseline_placefield_computation'], active_session_computation_configs=None) # can override `active_session_computation_configs` if we want to set custom ones like only the laps.)
_test_out

# global_batch_run.execute_session(session_context=curr_sess_context, force_reload=True, skip_extended_batch_computations=True, **{'computation_functions_name_includelist': ['_perform_baseline_placefield_computation'], 'active_session_computation_configs': None}) # can override `active_session_computation_configs` if we want to set custom ones like only the laps.)

# 23.5s

In [ ]:

full_good_dirs = [k for k, v in global_batch_run.session_batch_errors.items() if v is None]
bad_dirs = [k for k, v in global_batch_run.session_batch_errors.items() if v is not None]
full_good_dirs
bad_dirs

In [ ]:
global_batch_run.session_batch_status

In [ ]:
global_batch_run.session_batch_status
global_batch_run.session_batch_errors

# Get good sessions for use in the specific session processing notebook:

In [ ]:
batch_progress_df = global_batch_run.to_dataframe(expand_context=True, good_only=False) # all
good_only_batch_progress_df = global_batch_run.to_dataframe(expand_context=True, good_only=True)
good_only_batch_progress_df

In [ ]:
## Get the list of sessions that are completely ready to process:
full_good_ready_to_process_sessions = list(good_only_batch_progress_df['context'].to_numpy())
full_good_ready_to_process_sessions
# Get good sessions for use in the specific session processing notebook:

In [ ]:
run["good_sessions_list"].extend(full_good_ready_to_process_sessions)

In [ ]:
run.stop()
project.stop()

In [ ]:

print(",\n".join([ctx.get_initialization_code_string() for ctx in full_good_ready_to_process_sessions])) # List definitions

# [IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-08_14-26-15'),
# IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-09_1-22-43'),
# IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-12_15-55-31'),
# IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-13_14-42-6'),
# IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-07_16-40-19'),
# IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-12_16-53-46'),
# IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-09_17-29-30')]

In [ ]:
print("\ncurr_context = ".join([ctx.get_initialization_code_string() for ctx in full_good_ready_to_process_sessions])) # Line definitions

# curr_context = IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-08_14-26-15')
# curr_context = IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-09_1-22-43')
# curr_context = IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-12_15-55-31')
# curr_context = IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='one',session_name='2006-6-13_14-42-6')
# curr_context = IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-07_16-40-19')
# curr_context = IdentifyingContext(format_name='kdiba',animal='gor01',exper_name='two',session_name='2006-6-12_16-53-46')
# curr_context = IdentifyingContext(format_name='kdiba',animal='vvp01',exper_name='one',session_name='2006-4-09_17-29-30')

In [ ]:
good_only_batch_progress_df

In [ ]:
from datetime import datetime

# datetime object containing current date and time
save_time = datetime.now()
 
print("save_time =", save_time)

# dd/mm/YY H:M:S
dt_string = save_time.strftime("%Y-%m-%d_%I-%M%p")
print("date and time =", dt_string)

In [ ]:
## Get output file paths:
completed_pipeline_filename = 'loadedSessPickle.pkl'
completed_global_computations_filename = 'outputs/global_computation_results.pkl'

full_good_ready_to_process_session_paths = list(good_only_batch_progress_df['basedirs'].to_numpy())
session_paths_output_folders = [sess_path.joinpath('outputs').resolve() for sess_path in full_good_ready_to_process_session_paths]



completed_pipeline_file_paths = [sess_path.joinpath(completed_pipeline_filename).resolve() for sess_path in full_good_ready_to_process_session_paths]
completed_global_computations_file_paths = [sess_path.joinpath(completed_global_computations_filename).resolve() for sess_path in full_good_ready_to_process_session_paths]
completed_global_computations_file_paths